In [1]:
import numpy as np
aa = np.array([1,2,3,4,5,6,7,8])
print(aa)
print ( "THE TYPE IS" , type(aa) )

[1 2 3 4 5 6 7 8]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 1


In [2]:
bb = np.array ([ [11,12,13,14] , [15,16,17,18] ])
print(bb)
print ( "THE TYPE IS" , type(bb) )

[[11 12 13 14]
 [15 16 17 18]]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 2


In [3]:
cc = np.zeros((4,6))
print(cc)
print ( "THE TYPE IS" , type(cc) )

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 2


In [4]:
dd = np.ones((4,6))
print(dd)
print ( "THE TYPE IS" , type(dd) )

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 2


In [5]:
ee = np.identity(4)
print(ee)
print ( "THE TYPE IS" , type(ee) )

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 2


In [6]:
ff = np.arange(11)
print(ff)
print ( "THE TYPE IS" , type(ff) )

[ 0  1  2  3  4  5  6  7  8  9 10]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 1


In [7]:
gg = np.arange(11,21)
print(gg)
print ( "THE TYPE IS" , type(gg) )

[11 12 13 14 15 16 17 18 19 20]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 1


In [8]:
hh = np.arange(21,41,2)
print(hh)
print ( "THE TYPE IS" , type(hh) )

[21 23 25 27 29 31 33 35 37 39]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 1


In [9]:
kk = np.arange(-10,0)
print(kk)
print ( "THE TYPE IS" , type(kk) )

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 1


In [10]:
ll = np.linspace(21,30,19)
print(ll)
print ( "THE TYPE IS" , type(ll) )

[21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30. ]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 1


In [11]:
mm = np.linspace(0,96,17)
print(mm)
print ( "THE TYPE IS" , type(mm) )

[ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54. 60. 66. 72. 78. 84. 90. 96.]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 1


In [12]:
nn = mm.copy()
print(nn)
print ( "THE TYPE IS" , type(nn) )

[ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54. 60. 66. 72. 78. 84. 90. 96.]
THE TYPE IS <class 'numpy.ndarray'>
THE DIMENSION OF ARRAY IS 1
