In [1]:
import numpy as np
aa = np.arange(1,25).reshape(4,6)
print(aa)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [2]:
bb = np.arange(25,37)
print(bb)

[25 26 27 28 29 30 31 32 33 34 35 36]


In [3]:
print ( aa[2,3] )

16


In [8]:
print ( aa[2,:] )

[13 14 15 16 17 18]


In [9]:
print ( aa[:,3] )

[ 4 10 16 22]


In [10]:
print ( aa[:2,:] )

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
print ( aa[:,:3] )

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


In [15]:
print ( aa[1:3,2:4] )

[[ 9 10]
 [15 16]]


In [16]:
print ( aa[2:4,4:6] )

[[17 18]
 [23 24]]


In [17]:
print ( bb[3] )

28


In [18]:
print ( bb[-3] )

34


In [19]:
print ( bb[0:12:2] )

[25 27 29 31 33 35]


In [20]:
print ( bb[1::2] )

[26 28 30 32 34 36]


In [21]:
print ( bb[::3] )

[25 28 31 34]


In [22]:
print ( bb[4:8] )

[29 30 31 32]


In [23]:
print ( bb[-8:-4] )

[29 30 31 32]


In [24]:
for x in aa:
    print(x)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]
[13 14 15 16 17 18]
[19 20 21 22 23 24]


In [25]:
for x in aa:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [26]:
for x in np.nditer(aa):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
