In [1]:
import numpy as np
aa = np.array([1,2,3,4,5,6,7,8])
print(aa)
print ( "THE TYPE IS" , type(aa) ) 
print ( "THE SHAPE OF ARRAY IS" , aa.shape )
print ( "THE DIMENSION OF ARRAY IS" , aa.ndim )
print ( "THE SIZE OF ARRAY IS" , aa.size )
print ( "THE ITEM SIZE OF ARRAY IS" , aa.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , aa.dtype )

[1 2 3 4 5 6 7 8]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (8,)
THE DIMENSION OF ARRAY IS 1
THE SIZE OF ARRAY IS 8
THE ITEM SIZE OF ARRAY IS 4
THE DATA TYPE OF ARRAY IS int32


In [2]:
bb = np.array ([ [11,12,13,14] , [15,16,17,18] ])
print(bb)
print ( "THE TYPE IS" , type(bb) )
print ( "THE SHAPE OF ARRAY IS" , bb.shape )
print ( "THE DIMENSION OF ARRAY IS" , bb.ndim )
print ( "THE SIZE OF ARRAY IS" , bb.size )
print ( "THE ITEM SIZE OF ARRAY IS" , bb.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , bb.dtype )

[[11 12 13 14]
 [15 16 17 18]]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (2, 4)
THE DIMENSION OF ARRAY IS 2
THE SIZE OF ARRAY IS 8
THE ITEM SIZE OF ARRAY IS 4
THE DATA TYPE OF ARRAY IS int32


In [3]:
cc = np.zeros((4,6))
print(cc)
print ( "THE TYPE IS" , type(cc) )
print ( "THE SHAPE OF ARRAY IS" , cc.shape )
print ( "THE DIMENSION OF ARRAY IS" , cc.ndim )
print ( "THE SIZE OF ARRAY IS" , cc.size )
print ( "THE ITEM SIZE OF ARRAY IS" , cc.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , cc.dtype )

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (4, 6)
THE DIMENSION OF ARRAY IS 2
THE SIZE OF ARRAY IS 24
THE ITEM SIZE OF ARRAY IS 8
THE DATA TYPE OF ARRAY IS float64


In [4]:
dd = np.ones((4,6))
print(dd)
print ( "THE TYPE IS" , type(dd) )
print ( "THE SHAPE OF ARRAY IS" , dd.shape )
print ( "THE DIMENSION OF ARRAY IS" , dd.ndim )
print ( "THE SIZE OF ARRAY IS" , dd.size )
print ( "THE ITEM SIZE OF ARRAY IS" , dd.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , dd.dtype )

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (4, 6)
THE DIMENSION OF ARRAY IS 2
THE SIZE OF ARRAY IS 24
THE ITEM SIZE OF ARRAY IS 8
THE DATA TYPE OF ARRAY IS float64


In [5]:
ee = np.identity(4)
print(ee)
print ( "THE TYPE IS" , type(ee) )
print ( "THE SHAPE OF ARRAY IS" , ee.shape )
print ( "THE DIMENSION OF ARRAY IS" , ee.ndim )
print ( "THE SIZE OF ARRAY IS" , ee.size )
print ( "THE ITEM SIZE OF ARRAY IS" , ee.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , ee.dtype )

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (4, 4)
THE DIMENSION OF ARRAY IS 2
THE SIZE OF ARRAY IS 16
THE ITEM SIZE OF ARRAY IS 8
THE DATA TYPE OF ARRAY IS float64


In [6]:
ff = np.arange(11)
print(ff)
print ( "THE TYPE IS" , type(ff) )
print ( "THE SHAPE OF ARRAY IS" , ff.shape )
print ( "THE DIMENSION OF ARRAY IS" , ff.ndim )
print ( "THE SIZE OF ARRAY IS" , ff.size )
print ( "THE ITEM SIZE OF ARRAY IS" , ff.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , ff.dtype )

[ 0  1  2  3  4  5  6  7  8  9 10]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (11,)
THE DIMENSION OF ARRAY IS 1
THE SIZE OF ARRAY IS 11
THE ITEM SIZE OF ARRAY IS 4
THE DATA TYPE OF ARRAY IS int32


In [7]:
gg = np.arange(11,21)
print(gg)
print ( "THE TYPE IS" , type(gg) )
print ( "THE SHAPE OF ARRAY IS" , gg.shape )
print ( "THE DIMENSION OF ARRAY IS" , gg.ndim )
print ( "THE SIZE OF ARRAY IS" , gg.size )
print ( "THE ITEM SIZE OF ARRAY IS" , gg.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , gg.dtype )

[11 12 13 14 15 16 17 18 19 20]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (10,)
THE DIMENSION OF ARRAY IS 1
THE SIZE OF ARRAY IS 10
THE ITEM SIZE OF ARRAY IS 4
THE DATA TYPE OF ARRAY IS int32


In [8]:
hh = np.arange(21,41,2)
print(hh)
print ( "THE TYPE IS" , type(hh) )
print ( "THE SHAPE OF ARRAY IS" , hh.shape )
print ( "THE DIMENSION OF ARRAY IS" , hh.ndim )
print ( "THE SIZE OF ARRAY IS" , hh.size )
print ( "THE ITEM SIZE OF ARRAY IS" , hh.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , hh.dtype )

[21 23 25 27 29 31 33 35 37 39]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (10,)
THE DIMENSION OF ARRAY IS 1
THE SIZE OF ARRAY IS 10
THE ITEM SIZE OF ARRAY IS 4
THE DATA TYPE OF ARRAY IS int32


In [9]:
kk = np.arange(-10,0)
print(kk)
print ( "THE TYPE IS" , type(kk) )
print ( "THE SHAPE OF ARRAY IS" , kk.shape )
print ( "THE DIMENSION OF ARRAY IS" , kk.ndim )
print ( "THE SIZE OF ARRAY IS" , kk.size )
print ( "THE ITEM SIZE OF ARRAY IS" , kk.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , kk.dtype )

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (10,)
THE DIMENSION OF ARRAY IS 1
THE SIZE OF ARRAY IS 10
THE ITEM SIZE OF ARRAY IS 4
THE DATA TYPE OF ARRAY IS int32


In [10]:
ll = np.linspace(21,30,19)
print(ll)
print ( "THE TYPE IS" , type(ll) )
print ( "THE SHAPE OF ARRAY IS" , ll.shape )
print ( "THE DIMENSION OF ARRAY IS" , ll.ndim )
print ( "THE SIZE OF ARRAY IS" , ll.size )
print ( "THE ITEM SIZE OF ARRAY IS" , ll.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , ll.dtype )

[21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30. ]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (19,)
THE DIMENSION OF ARRAY IS 1
THE SIZE OF ARRAY IS 19
THE ITEM SIZE OF ARRAY IS 8
THE DATA TYPE OF ARRAY IS float64


In [11]:
mm = np.linspace(0,96,17)
print(mm)
print ( "THE TYPE IS" , type(mm) )
print ( "THE SHAPE OF ARRAY IS" , mm.shape )
print ( "THE DIMENSION OF ARRAY IS" , mm.ndim )
print ( "THE SIZE OF ARRAY IS" , mm.size )
print ( "THE ITEM SIZE OF ARRAY IS" , mm.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , mm.dtype )

[ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54. 60. 66. 72. 78. 84. 90. 96.]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (17,)
THE DIMENSION OF ARRAY IS 1
THE SIZE OF ARRAY IS 17
THE ITEM SIZE OF ARRAY IS 8
THE DATA TYPE OF ARRAY IS float64


In [12]:
nn = mm.copy()
print(nn)
print ( "THE TYPE IS" , type(nn) )
print ( "THE SHAPE OF ARRAY IS" , nn.shape )
print ( "THE DIMENSION OF ARRAY IS" , nn.ndim )
print ( "THE SIZE OF ARRAY IS" , nn.size )
print ( "THE ITEM SIZE OF ARRAY IS" , nn.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , nn.dtype )

[ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54. 60. 66. 72. 78. 84. 90. 96.]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (17,)
THE DIMENSION OF ARRAY IS 1
THE SIZE OF ARRAY IS 17
THE ITEM SIZE OF ARRAY IS 8
THE DATA TYPE OF ARRAY IS float64


In [13]:
pp = np.array ([ [ [31,32,33,34] , [35,36,37,38] , [39,40,41,42] ] , [ [43,44,45,46]  , [47,48,49,50] , [51,52,53,54] ] ])
print(pp)
print ( "THE TYPE IS" , type(pp) )
print ( "THE SHAPE OF ARRAY IS" , pp.shape )
print ( "THE DIMENSION OF ARRAY IS" , pp.ndim )
print ( "THE SIZE OF ARRAY IS" , pp.size )
print ( "THE ITEM SIZE OF ARRAY IS" , pp.itemsize )
print ( "THE DATA TYPE OF ARRAY IS" , pp.dtype )

[[[31 32 33 34]
  [35 36 37 38]
  [39 40 41 42]]

 [[43 44 45 46]
  [47 48 49 50]
  [51 52 53 54]]]
THE TYPE IS <class 'numpy.ndarray'>
THE SHAPE OF ARRAY IS (2, 3, 4)
THE DIMENSION OF ARRAY IS 3
THE SIZE OF ARRAY IS 24
THE ITEM SIZE OF ARRAY IS 4
THE DATA TYPE OF ARRAY IS int32


In [14]:
aa = np.array([1,2,3,4,5,6,7,8])
print(aa)
print ( aa.astype("float") )

[1 2 3 4 5 6 7 8]
[1. 2. 3. 4. 5. 6. 7. 8.]


In [15]:
bb = np.array ([ [11,12,13,14] , [15,16,17,18] ])
print(bb)
print ( bb.astype("str") )

[[11 12 13 14]
 [15 16 17 18]]
[['11' '12' '13' '14']
 ['15' '16' '17' '18']]


In [16]:
cc = np.zeros((4,6))
print(cc)
print ( cc.astype("int") )

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
