In [1]:
import numpy as np
aa = np.array ([ [ [31,32,33,34] , [35,36,37,38] , [39,40,41,42] ] , [ [43,44,45,46]  , [47,48,49,50] , [51,52,53,54] ] ])
print(aa)

[[[31 32 33 34]
  [35 36 37 38]
  [39 40 41 42]]

 [[43 44 45 46]
  [47 48 49 50]
  [51 52 53 54]]]


In [2]:
print ( aa.ndim )

3


In [3]:
print ( aa.shape )

(2, 3, 4)


In [4]:
print ( aa.ravel() )

[31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [5]:
print ( aa.ravel().ndim )

1


In [6]:
print ( aa.ravel().shape )

(24,)


In [7]:
bb = np.array ([ [11,12,13,14] , [15,16,17,18] ])
print(bb)

[[11 12 13 14]
 [15 16 17 18]]


In [8]:
print ( bb.ndim )

2


In [9]:
print ( bb.shape )

(2, 4)


In [10]:
print ( bb.transpose() )

[[11 15]
 [12 16]
 [13 17]
 [14 18]]


In [11]:
print ( bb.transpose().ndim )

2


In [12]:
print ( bb.transpose().shape )

(4, 2)


In [13]:
cc = np.arange(13,19).reshape(2,3)
print(cc)

[[13 14 15]
 [16 17 18]]


In [14]:
dd = np.arange(19,25).reshape(2,3)
print(dd)

[[19 20 21]
 [22 23 24]]


In [15]:
print ( np.stack ((cc,dd)) )

[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]


In [16]:
print ( np.hstack ((cc,dd)) )

[[13 14 15 19 20 21]
 [16 17 18 22 23 24]]


In [17]:
print ( np.vstack ((cc,dd)) )

[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]


In [18]:
print ( np.dstack ((cc,dd)) )

[[[13 19]
  [14 20]
  [15 21]]

 [[16 22]
  [17 23]
  [18 24]]]


In [19]:
ee = np.arange(25,49).reshape(4,6)
print(ee)

[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [20]:
print ( np.hsplit (ee,3) )

[array([[25, 26],
       [31, 32],
       [37, 38],
       [43, 44]]), array([[27, 28],
       [33, 34],
       [39, 40],
       [45, 46]]), array([[29, 30],
       [35, 36],
       [41, 42],
       [47, 48]])]


In [21]:
print ( np.vsplit (ee,2) )

[array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]]), array([[37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48]])]


In [22]:
print ( np.hsplit (ee,6) )

[array([[25],
       [31],
       [37],
       [43]]), array([[26],
       [32],
       [38],
       [44]]), array([[27],
       [33],
       [39],
       [45]]), array([[28],
       [34],
       [40],
       [46]]), array([[29],
       [35],
       [41],
       [47]]), array([[30],
       [36],
       [42],
       [48]])]


In [23]:
print ( np.vsplit (ee,4) )

[array([[25, 26, 27, 28, 29, 30]]), array([[31, 32, 33, 34, 35, 36]]), array([[37, 38, 39, 40, 41, 42]]), array([[43, 44, 45, 46, 47, 48]])]


In [24]:
aa = np.array ([ [ [31,32,33,34] , [35,36,37,38] , [39,40,41,42] ] , [ [43,44,45,46]  , [47,48,49,50] , [51,52,53,54] ] ])
print ( np.hsplit (aa,3) )

[array([[[31, 32, 33, 34]],

       [[43, 44, 45, 46]]]), array([[[35, 36, 37, 38]],

       [[47, 48, 49, 50]]]), array([[[39, 40, 41, 42]],

       [[51, 52, 53, 54]]])]


In [25]:
aa = np.array ([ [ [31,32,33,34] , [35,36,37,38] , [39,40,41,42] ] , [ [43,44,45,46]  , [47,48,49,50] , [51,52,53,54] ] ])
print ( np.vsplit (aa,2) )

[array([[[31, 32, 33, 34],
        [35, 36, 37, 38],
        [39, 40, 41, 42]]]), array([[[43, 44, 45, 46],
        [47, 48, 49, 50],
        [51, 52, 53, 54]]])]


In [26]:
aa = np.array ([ [ [31,32,33,34] , [35,36,37,38] , [39,40,41,42] ] , [ [43,44,45,46]  , [47,48,49,50] , [51,52,53,54] ] ])
print ( np.dsplit (aa,4) )

[array([[[31],
        [35],
        [39]],

       [[43],
        [47],
        [51]]]), array([[[32],
        [36],
        [40]],

       [[44],
        [48],
        [52]]]), array([[[33],
        [37],
        [41]],

       [[45],
        [49],
        [53]]]), array([[[34],
        [38],
        [42]],

       [[46],
        [50],
        [54]]])]


In [27]:
print ( aa.reshape(3,2,4) )

[[[31 32 33 34]
  [35 36 37 38]]

 [[39 40 41 42]
  [43 44 45 46]]

 [[47 48 49 50]
  [51 52 53 54]]]


In [28]:
print ( aa.reshape(4,3,2) )

[[[31 32]
  [33 34]
  [35 36]]

 [[37 38]
  [39 40]
  [41 42]]

 [[43 44]
  [45 46]
  [47 48]]

 [[49 50]
  [51 52]
  [53 54]]]


In [29]:
print ( aa.reshape(3,4,2) )

[[[31 32]
  [33 34]
  [35 36]
  [37 38]]

 [[39 40]
  [41 42]
  [43 44]
  [45 46]]

 [[47 48]
  [49 50]
  [51 52]
  [53 54]]]
