In [1]:
import numpy as np
aa = np.array ([54,60,66,72,78,84,90,96])
bb = np.array ([12,16,20,24,28,32,36,40])
print ( aa + bb )

[ 66  76  86  96 106 116 126 136]


In [2]:
aa = np.array ([54,60,66,72,78,84,90,96])
bb = np.array ([12,16,20,24,28,32,36,40])
print ( aa * bb )

[ 648  960 1320 1728 2184 2688 3240 3840]


In [3]:
aa = np.array ([54,60,66,72,78,84,90,96])
bb = np.array ([12,16,20,24,28,32,36,40])
print ( aa - bb )

[42 44 46 48 50 52 54 56]


In [4]:
aa = np.array ([54,60,66,72,78,84,90,96])
bb = np.array ([12,16,20,24,28,32,36,40])
print ( bb - aa )

[-42 -44 -46 -48 -50 -52 -54 -56]


In [5]:
aa = np.array ([54,60,66,72,78,84,90,96])
print ( aa * 3 )

[162 180 198 216 234 252 270 288]


In [6]:
bb = np.array ([12,16,20,24,28,32,36,40])
print ( bb ** 3 )

[ 1728  4096  8000 13824 21952 32768 46656 64000]


In [7]:
aa = np.array ([54,60,66,72,78,84,90,96])
print ( aa > 74 )

[False False False False  True  True  True  True]


In [8]:
bb = np.array ([12,16,20,24,28,32,36,40])
print ( bb < 26 )

[ True  True  True  True False False False False]


In [9]:
aa = np.array ([54,60,66,72,78,84,90,96])
print ( aa >= 72 )

[False False False  True  True  True  True  True]


In [10]:
bb = np.array ([12,16,20,24,28,32,36,40])
print ( bb <= 28 )

[ True  True  True  True  True False False False]


In [11]:
cc = np.arange(31,37).reshape(2,3)
print(cc)

[[31 32 33]
 [34 35 36]]


In [12]:
dd = np.arange(37,43).reshape(3,2)
print(dd)

[[37 38]
 [39 40]
 [41 42]]


In [13]:
cc = np.arange(31,37).reshape(2,3)
dd = np.arange(37,43).reshape(3,2)

print ( cc.dot(dd) )

[[3748 3844]
 [4099 4204]]


In [14]:
cc = np.arange(31,37).reshape(2,3)
dd = np.arange(37,43).reshape(3,2)

print ( dd.dot(cc) )

[[2439 2514 2589]
 [2569 2648 2727]
 [2699 2782 2865]]


In [15]:
ee = np.arange(37,85).reshape(6,8)
print(ee)

[[37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52]
 [53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68]
 [69 70 71 72 73 74 75 76]
 [77 78 79 80 81 82 83 84]]


In [16]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.min() )

37


In [17]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.max() )

84


In [18]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.min(axis=0) )

[37 38 39 40 41 42 43 44]


In [19]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.min(axis=1) )

[37 45 53 61 69 77]


In [20]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.max(axis=0) )

[77 78 79 80 81 82 83 84]


In [21]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.max(axis=1) )

[44 52 60 68 76 84]


In [22]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.sum() )

2904


In [23]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.sum(axis=0) )

[342 348 354 360 366 372 378 384]


In [24]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.sum(axis=1) )

[324 388 452 516 580 644]


In [25]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.mean() )

60.5


In [26]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.mean(axis=0) )

[57. 58. 59. 60. 61. 62. 63. 64.]


In [27]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.mean(axis=1) )

[40.5 48.5 56.5 64.5 72.5 80.5]


In [28]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.std() )

13.853399101544236


In [29]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.std(axis=0) )

[13.66260102 13.66260102 13.66260102 13.66260102 13.66260102 13.66260102
 13.66260102 13.66260102]


In [30]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.std(axis=1) )

[2.29128785 2.29128785 2.29128785 2.29128785 2.29128785 2.29128785]


In [31]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.var() )

191.91666666666666


In [32]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.var(axis=0) )

[186.66666667 186.66666667 186.66666667 186.66666667 186.66666667
 186.66666667 186.66666667 186.66666667]


In [33]:
ee = np.arange(37,85).reshape(6,8)
print ( ee.var(axis=1) )

[5.25 5.25 5.25 5.25 5.25 5.25]


In [34]:
ee = np.arange(37,85).reshape(6,8)
print ( np.median(ee) )

60.5


In [35]:
ee = np.arange(37,85).reshape(6,8)
print ( np.median ( ee, axis=0 ) )

[57. 58. 59. 60. 61. 62. 63. 64.]


In [36]:
ee = np.arange(37,85).reshape(6,8)
print ( np.median ( ee, axis=1 ) )

[40.5 48.5 56.5 64.5 72.5 80.5]


In [37]:
ee = np.arange(37,85).reshape(6,8)
print ( np.sin(ee) )

[[-0.64353813  0.29636858  0.96379539  0.74511316 -0.15862267 -0.91652155
  -0.83177474  0.01770193]
 [ 0.85090352  0.90178835  0.12357312 -0.76825466 -0.95375265 -0.26237485
   0.67022918  0.98662759]
 [ 0.39592515 -0.55878905 -0.99975517 -0.521551    0.43616476  0.99287265
   0.63673801 -0.30481062]
 [-0.96611777 -0.7391807   0.1673557   0.92002604  0.82682868 -0.02655115
  -0.85551998 -0.89792768]
 [-0.11478481  0.77389068  0.95105465  0.25382336 -0.67677196 -0.98514626
  -0.38778164  0.56610764]
 [ 0.99952016  0.51397846 -0.44411267 -0.99388865 -0.62988799  0.31322878
   0.96836446  0.73319032]]


In [38]:
ee = np.arange(37,85).reshape(6,8)
print ( np.cos(ee) )

[[ 0.76541405  0.95507364  0.26664293 -0.66693806 -0.98733928 -0.39998531
   0.5551133   0.99984331]
 [ 0.52532199 -0.43217794 -0.99233547 -0.64014434  0.30059254  0.96496603
   0.7421542  -0.16299078]
 [-0.91828279 -0.82930983  0.02212676  0.85322011  0.89986683  0.11918014
  -0.77108022 -0.95241298]
 [-0.25810164  0.67350716  0.98589658  0.39185723 -0.56245385 -0.99964746
  -0.5177698   0.44014302]
 [ 0.99339038  0.6333192  -0.30902273 -0.96725059 -0.73619272  0.17171734
   0.92175127  0.82433133]
 [-0.03097503 -0.85780309 -0.89597095 -0.11038724  0.77668598  0.9496777
   0.24954012 -0.6800235 ]]


In [39]:
ee = np.arange(37,85).reshape(6,8)
print ( np.tan(ee) )

[[-8.40771255e-01  3.10309661e-01  3.61455441e+00 -1.11721493e+00
   1.60656699e-01  2.29138799e+00 -1.49838734e+00  1.77046993e-02]
 [ 1.61977519e+00 -2.08661353e+00 -1.24527568e-01  1.20012724e+00
  -3.17290855e+00 -2.71900612e-01  9.03086149e-01 -6.05327238e+00]
 [-4.31158197e-01  6.73800101e-01 -4.51830879e+01 -6.11273688e-01
   4.84699227e-01  8.33085685e+00 -8.25774009e-01  3.20040389e-01]
 [ 3.74316794e+00 -1.09750978e+00  1.69749752e-01  2.34786031e+00
  -1.47003826e+00  2.65605178e-02  1.65231726e+00 -2.04008160e+00]
 [-1.15548546e-01  1.22195992e+00 -3.07762040e+00 -2.62417378e-01
   9.19286404e-01 -5.73702254e+00 -4.20700951e-01  6.86747689e-01]
 [-3.22685758e+01 -5.99179998e-01  4.95677533e-01  9.00365495e+00
  -8.10994416e-01  3.29826407e-01  3.88059631e+00 -1.07818381e+00]]


In [40]:
ee = np.arange(37,85).reshape(6,8)
print ( np.exp(ee) )

[[1.17191424e+16 3.18559318e+16 8.65934004e+16 2.35385267e+17
  6.39843494e+17 1.73927494e+18 4.72783947e+18 1.28516001e+19]
 [3.49342711e+19 9.49611942e+19 2.58131289e+20 7.01673591e+20
  1.90734657e+21 5.18470553e+21 1.40934908e+22 3.83100800e+22]
 [1.04137594e+23 2.83075330e+23 7.69478527e+23 2.09165950e+24
  5.68572000e+24 1.54553894e+25 4.20121040e+25 1.14200739e+26]
 [3.10429794e+26 8.43835667e+26 2.29378316e+27 6.23514908e+27
  1.69488924e+28 4.60718663e+28 1.25236317e+29 3.40427605e+29]
 [9.25378173e+29 2.51543867e+30 6.83767123e+30 1.85867175e+31
  5.05239363e+31 1.37338298e+32 3.73324200e+32 1.01480039e+33]
 [2.75851345e+33 7.49841700e+33 2.03828107e+34 5.54062238e+34
  1.50609731e+35 4.09399696e+35 1.11286375e+36 3.02507732e+36]]


In [41]:
ee = np.arange(37,85).reshape(6,8)
print ( np.log(ee) )

[[3.61091791 3.63758616 3.66356165 3.68887945 3.71357207 3.73766962
  3.76120012 3.78418963]
 [3.80666249 3.8286414  3.8501476  3.87120101 3.8918203  3.91202301
  3.93182563 3.95124372]
 [3.97029191 3.98898405 4.00733319 4.02535169 4.04305127 4.06044301
  4.07753744 4.09434456]
 [4.11087386 4.12713439 4.14313473 4.15888308 4.17438727 4.18965474
  4.20469262 4.21950771]
 [4.2341065  4.24849524 4.26267988 4.27666612 4.29045944 4.30406509
  4.31748811 4.33073334]
 [4.34380542 4.35670883 4.36944785 4.38202663 4.39444915 4.40671925
  4.41884061 4.4308168 ]]


In [42]:
ee = np.arange(37,85).reshape(6,8)
print ( np.sqrt(ee) )

[[6.08276253 6.164414   6.244998   6.32455532 6.40312424 6.4807407
  6.55743852 6.63324958]
 [6.70820393 6.78232998 6.8556546  6.92820323 7.         7.07106781
  7.14142843 7.21110255]
 [7.28010989 7.34846923 7.41619849 7.48331477 7.54983444 7.61577311
  7.68114575 7.74596669]
 [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
  8.18535277 8.24621125]
 [8.30662386 8.36660027 8.42614977 8.48528137 8.54400375 8.60232527
  8.66025404 8.71779789]
 [8.77496439 8.83176087 8.88819442 8.94427191 9.         9.05538514
  9.11043358 9.16515139]]


In [43]:
aa = np.array ([54,60,66,72,78,84,90,96])
bb = np.array ([12,16,20,24,28,32,36,40])
print ( aa / bb )

[4.5        3.75       3.3        3.         2.78571429 2.625
 2.5        2.4       ]


In [44]:
aa = np.array ([54,60,66,72,78,84,90,96])
bb = np.array ([12,16,20,24,28,32,36,40])
print ( bb / aa )

[0.22222222 0.26666667 0.3030303  0.33333333 0.35897436 0.38095238
 0.4        0.41666667]


In [45]:
aa = np.array ([54,60,66,72,78,84,90,96])
bb = np.array ([12,16,20,24,28,32,36,40])
print ( aa % bb )

[ 6 12  6  0 22 20 18 16]


In [46]:
aa = np.array ([54,60,66,72,78,84,90,96])
bb = np.array ([12,16,20,24,28,32,36,40])
print ( aa // bb )

[4 3 3 3 2 2 2 2]
