In [1]:
import numpy as np
aa = np.arange(17,33).reshape(4,4)
print(aa)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [2]:
bb = np.arange(11,15).reshape(1,4)
print(bb)

[[11 12 13 14]]


In [3]:
cc = np.arange(15,19).reshape(4,1)
print(cc)

[[15]
 [16]
 [17]
 [18]]


In [4]:
print ( aa + bb )

[[28 30 32 34]
 [32 34 36 38]
 [36 38 40 42]
 [40 42 44 46]]


In [5]:
print ( aa + cc )

[[32 33 34 35]
 [37 38 39 40]
 [42 43 44 45]
 [47 48 49 50]]


In [6]:
print ( bb + cc )

[[26 27 28 29]
 [27 28 29 30]
 [28 29 30 31]
 [29 30 31 32]]


In [7]:
dd = np.arange(104,200,4).reshape(6,4)
print(dd)

[[104 108 112 116]
 [120 124 128 132]
 [136 140 144 148]
 [152 156 160 164]
 [168 172 176 180]
 [184 188 192 196]]


In [8]:
ee = np.arange(50,51).reshape(1,1)
print(ee)

[[50]]


In [9]:
print ( dd + ee )

[[154 158 162 166]
 [170 174 178 182]
 [186 190 194 198]
 [202 206 210 214]
 [218 222 226 230]
 [234 238 242 246]]


In [10]:
print ( ee + dd )

[[154 158 162 166]
 [170 174 178 182]
 [186 190 194 198]
 [202 206 210 214]
 [218 222 226 230]
 [234 238 242 246]]


In [11]:
ff = np.arange(301,307).reshape(1,6)
print(ff)

[[301 302 303 304 305 306]]


In [12]:
gg = np.arange(201,207).reshape(6,1)
print(gg)

[[201]
 [202]
 [203]
 [204]
 [205]
 [206]]


In [13]:
print ( ff + gg )

[[502 503 504 505 506 507]
 [503 504 505 506 507 508]
 [504 505 506 507 508 509]
 [505 506 507 508 509 510]
 [506 507 508 509 510 511]
 [507 508 509 510 511 512]]
