In [1]:
import numpy as np
xyz = np.random.randint ( low=1 , high=101 , size=24 ).reshape(4,6)
print(xyz)

[[ 48 100  24  71  90   2]
 [ 67  90  83  13  97  53]
 [ 73   4  84  43  89  91]
 [ 69  14  57   8  20  78]]


In [2]:
print ( xyz[3] )

[69 14 57  8 20 78]


In [3]:
print ( xyz[1][2] )

83


In [4]:
print ( xyz>50 )

[[False  True False  True  True False]
 [ True  True  True False  True  True]
 [ True False  True False  True  True]
 [ True False  True False False  True]]


In [5]:
print ( xyz<51 )

[[ True False  True False False  True]
 [False False False  True False False]
 [False  True False  True False False]
 [False  True False  True  True False]]


In [6]:
print ( (xyz>50).shape )

(4, 6)


In [7]:
print ( (xyz<51).shape )

(4, 6)


In [8]:
print ( xyz [xyz>50] )

[100  71  90  67  90  83  97  53  73  84  89  91  69  57  78]


In [9]:
print ( xyz [xyz<51] )

[48 24  2 13  4 43 14  8 20]


In [10]:
print ( xyz [ ( xyz > 20 ) & ( xyz < 81 ) ] )

[48 24 71 67 53 73 43 69 57 78]


In [11]:
print ( xyz [ ( xyz % 2 != 0 ) & ( xyz % 3 != 0 ) ] )

[71 67 83 13 97 53 73 43 89 91]


In [12]:
print ( xyz [ ( xyz % 2 != 0 ) | ( xyz % 3 != 0 ) ] )

[100  71   2  67  83  13  97  53  73   4  43  89  91  69  14  57   8  20]


In [13]:
xyz [ ( xyz % 2 != 0 ) & ( xyz % 3 != 0 ) ] = 0 
print(xyz)

[[ 48 100  24   0  90   2]
 [  0  90   0   0   0   0]
 [  0   4  84   0   0   0]
 [ 69  14  57   8  20  78]]
