In [1]:
import numpy as np
xyz = np.arange(104,197,4).reshape(6,4)
print(xyz)

[[104 108 112 116]
 [120 124 128 132]
 [136 140 144 148]
 [152 156 160 164]
 [168 172 176 180]
 [184 188 192 196]]


In [2]:
print ( xyz [[1,2,4],:] )

[[120 124 128 132]
 [136 140 144 148]
 [168 172 176 180]]


In [3]:
print ( xyz [:,[0,1,3]] )

[[104 108 116]
 [120 124 132]
 [136 140 148]
 [152 156 164]
 [168 172 180]
 [184 188 196]]


In [4]:
print ( xyz [[1,2,4],[0,1,3]] )

[120 140 180]
