In [1]:
import numpy as np
aa = np.random.random() 
print(aa)

0.6953631282167964


In [2]:
bb = np.random.random() 
print(bb)

0.24982904156106134


In [3]:
np.random.seed(100)
cc = np.random.random() 
print(cc)

0.5434049417909654


In [4]:
np.random.seed(400)
dd = np.random.random() 
print(dd)

0.6687289088341747


In [5]:
np.random.seed((4,16))
ee = np.random.random() 
print(ee)

0.6586503598135198


In [6]:
np.random.seed((4,16,64))
ff = np.random.random() 
print(ff)

0.3352564369996247


In [7]:
gg = np.random.uniform(1,100) 
print(gg)

8.359262717910728


In [8]:
hh = np.random.uniform(1,100,24) 
print(hh)

[ 7.75822947  5.10445936  7.38521232 65.24159772 79.10025812 24.1846412
 37.89432628 38.40859937 61.86643199  6.64699935 16.86776751 29.09372458
 10.49386274 94.90754764 23.4688833  57.10230134 67.64373983 14.27651233
 10.25796065 39.91089831  7.9679984  54.2683582   6.90530211 14.16317803]


In [9]:
kk = np.random.uniform(1,100,24) .reshape(4,6) 
print(kk)

[[33.67361129 12.63990631 72.48849545 93.19658716 20.40697218 23.57632428]
 [43.3737823  51.46971282 64.41381701 70.34261365 84.07243833 16.28322308]
 [ 6.8127536  82.28993452 37.78756343 53.59959869 99.27080415 54.04712621]
 [68.19597074 54.09880115 16.84743973 37.96509789 25.36242132 23.06956556]]


In [10]:
mm = np.random.randint(1,9) 
print(mm)

5


In [11]:
nn = np.random.randint(1,9,20) 
print(nn)

[2 1 3 7 5 8 5 8 6 3 4 2 8 4 5 2 1 4 8 1]


In [12]:
pp = np.random.randint(1,9,20) .reshape(4,5) 
print(pp)

[[1 7 1 3 7]
 [6 8 5 5 8]
 [5 7 6 3 3]
 [8 8 4 7 8]]


In [13]:
qq = np.random.randint(31,61,6)
print(qq)

[37 58 49 33 41 57]


In [14]:
print ( np.max(qq) )

58


In [15]:
print ( np.min(qq) )

33


In [16]:
print ( np.argmax(qq) )

1


In [17]:
print ( np.argmin(qq) )

3


In [18]:
print ( qq [ np.argmax(qq) ] )

58


In [19]:
print ( qq [ np.argmin(qq) ] )

33


In [20]:
qq [ qq % 2 == 0 ] = 100
print(qq)

[ 37 100  49  33  41  57]


In [21]:
rr = np.random.randint(1,41,10)
print(rr)

[ 6 12 35 30 12 13 34 25 34 22]


In [22]:
print ( np.where ( rr%2==1 , 100 , rr ) )

[  6  12 100  30  12 100  34 100  34  22]


In [23]:
print(rr)

[ 6 12 35 30 12 13 34 25 34 22]


In [24]:
ss = np.where ( rr%2==1 , 100 , rr )
print(ss)

[  6  12 100  30  12 100  34 100  34  22]


In [25]:
tt = np.random.randint(101,201,20)
print(tt)

[115 130 189 194 137 131 105 103 186 130 128 153 142 182 137 161 129 103
 185 115]


In [26]:
tt = np.sort(tt)
print(tt)

[103 103 105 115 115 128 129 130 130 131 137 137 142 153 161 182 185 186
 189 194]


In [27]:
print ( np.percentile (tt,0) )

103.0


In [28]:
print ( np.percentile (tt,10) )

104.8


In [29]:
print ( np.percentile (tt,25) )

124.75


In [30]:
print ( np.percentile (tt,40) )

130.0


In [31]:
print ( np.percentile (tt,50) )

134.0


In [32]:
print ( np.percentile (tt,60) )

139.0


In [33]:
print ( np.percentile (tt,75) )

166.25


In [34]:
print ( np.percentile (tt,90) )

186.3


In [35]:
print ( np.percentile (tt,100) )

194.0
